Update .gitlab-ci.yml file

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -29,10 +29,17 @@ deploy:
     - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | base64 -d > ~/.ssh/id_rsa
     - chmod 600 ~/.ssh/id_rsa
     - ssh-keyscan -H 147.45.225.75 >> ~/.ssh/known_hosts
-    - ssh root@147.45.225.75 "docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD && \
-                                    docker pull $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:latest && \
-                                    docker-compose -f /root/docker-compose.yml up --no-deps -d $DOCKER_COMPOSE_CONTAINER_NAME && \
-                                    docker system prune -f && \
-                                    docker logout"
-  only:
+    - |
+      ssh user@your-server-address << 'EOF'
+      if ! command -v docker &> /dev/null
+      then
+          echo "Docker could not be found"
+          exit 1
+      fi
+      docker login -u $DOCKERHUB_USERNAME --password-stdin <<< "$DOCKERHUB_PASSWORD"
+      docker pull $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:latest
+      docker-compose -f /root/docker-compose.yml up --no-deps -d $DOCKER_COMPOSE_CONTAINER_NAME
+      docker system prune -f
+      docker logout
+      EOF  only:
     - production
