Update .gitlab-ci.yml file

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -23,6 +23,7 @@ build:
   before_script:
     - cp ${ENV_FILE} .env.local
   script:
+  script:
     - docker build --no-cache -t "$DOCKERHUB_USERNAME/$DOCKERHUB_REPO:latest" .
 
 deploy:
@@ -51,12 +52,27 @@ deploy:
        echo "DOCKERHUB_USERNAME: $DOCKERHUB_USERNAME"
        echo "DOCKERHUB_REPO: $DOCKERHUB_REPO"
        docker pull "$DOCKERHUB_USERNAME/$DOCKERHUB_REPO:latest"
+       docker logout
+      ssh -o LogLevel=QUIET -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@$SERVER_IP <<EOL
+       set -e
+       if ! command -v docker &> /dev/null; then
+           echo "Docker could not be found"
+           exit 1
+       fi
+       echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
+       docker pull "$DOCKERHUB_USERNAME/$DOCKERHUB_REPO:latest"
+       docker logout
+
+       if [ ! -f /root/docker-compose.yml ]; then
+           echo "docker-compose.yml not found"
+           exit 1
+       fi
        if [ ! -f /root/docker-compose.yml ]; then
            echo "docker-compose.yml not found"
            exit 1
        fi
 
-      docker-compose -f /root/docker-compose.yml up --no-deps -d "$DOCKER_COMPOSE_CONTAINER_NAME"
-      docker system prune -f
+       docker-compose -f /root/docker-compose.yml up --no-deps -d "$DOCKER_COMPOSE_CONTAINER_NAME"
+       docker system prune -f
   only:
     - master
